# Generated by Django 3.2.5 on 2021-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
