# Generated by Django 3.2.5 on 2021-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highfitapp', '0002_auto_20210813_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfit',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
